version: '3'
services:
  app:
    build: .
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://51.77.210.237:31012/faculte  # Utiliser le nom du conteneur postgres0
      - SPRING_DATASOURCE_USERNAME=spring
      - SPRING_DATASOURCE_PASSWORD=Yujsh98hdkksnx98c41c5152xx6x6x4xsjsjsjshnxxjsjsk
      - TZ=Africa/Tunis
    volumes:
      - ./uploads:/app/src/main/resources/static/uploads  # Volume pour persister les fichiers uploads
    networks:
      - faculte-reseau

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: Yujsh98hdkksnx98c41c5152xx6x6x4xsjsjsjshnxxjsjsk
      POSTGRES_DB: faculte
    networks:
      - faculte-reseau

networks:
  faculte-reseau:
    driver: bridge
